export type ModelData = Record<string, Record<string, { reasoning: boolean }>>;
export const SUPPORTED_MODELS: ModelData = {
    'openai': {
        'o1': { reasoning: true },
        'o1-2024-12-17': { reasoning: true },
        'o1-mini': { reasoning: true },
        'o1-mini-2024-09-12': { reasoning: true },
        'o1-preview': { reasoning: true },
        'o1-preview-2024-09-12': { reasoning: true },
        'o3-mini': { reasoning: true },
        'o3-mini-2025-01-31': { reasoning: true },
        'o3': { reasoning: true },
        'o3-2025-04-16': { reasoning: true },
        'o4-mini': { reasoning: true },
        'o4-mini-2025-04-16': { reasoning: true },
        'gpt-4.1': { reasoning: false },
        'gpt-4.1-2025-04-14': { reasoning: false },
        'gpt-4.1-mini': { reasoning: false },
        'gpt-4.1-mini-2025-04-14': { reasoning: false },
        'gpt-4.1-nano': { reasoning: false },
        'gpt-4.1-nano-2025-04-14': { reasoning: false },
        'gpt-4o': { reasoning: false },
        'gpt-4o-2024-05-13': { reasoning: false },
        'gpt-4o-2024-08-06': { reasoning: false },
        'gpt-4o-2024-11-20': { reasoning: false },
        'gpt-4o-audio-preview': { reasoning: false },
        'gpt-4o-audio-preview-2024-10-01': { reasoning: false },
        'gpt-4o-audio-preview-2024-12-17': { reasoning: false },
        'gpt-4o-search-preview': { reasoning: false },
        'gpt-4o-search-preview-2025-03-11': { reasoning: false },
        'gpt-4o-mini-search-preview': { reasoning: false },
        'gpt-4o-mini-search-preview-2025-03-11': { reasoning: false },
        'gpt-4o-mini': { reasoning: false },
        'gpt-4o-mini-2024-07-18': { reasoning: false },
        'gpt-4-turbo': { reasoning: false },
        'gpt-4-turbo-2024-04-09': { reasoning: false },
        'gpt-4-turbo-preview': { reasoning: false },
        'gpt-4-0125-preview': { reasoning: false },
        'gpt-4-1106-preview': { reasoning: false },
        'gpt-4': { reasoning: false },
        'gpt-4-0613': { reasoning: false },
        'gpt-4.5-preview': { reasoning: false },
        'gpt-4.5-preview-2025-02-27': { reasoning: false },
        'gpt-3.5-turbo-0125': { reasoning: false },
        'gpt-3.5-turbo': { reasoning: false },
        'gpt-3.5-turbo-1106': { reasoning: false },
        'chatgpt-4o-latest': { reasoning: false }
    }
}